language: python
python:
  - 3.7

env:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d

script:
  - flake8
  - pipenv run flake8 .

#after_success:
#  - codecov