language: python
python:
  - 3.8

env:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv codecov
  - pipenv sync -d

script:
  - pipenv run flake8 .
  - pytest curso-django --cov=curso-django

after_success:
  - codecov